/// Starter exercise library — spec Section 4 ("Curated exercise library
/// (~150-200 exercises)"). This is a real, usable starting set (68
/// exercises across all 7 categories) — same honest philosophy as the
/// food dataset: a working smaller library beats a padded fake one.
/// Growing this toward 150-200 is ongoing work, not a blocker for v1.
///
/// Fields match the `exercises` table columns exactly.
final List<Map<String, Object?>> exerciseSeed = [
  // ---- CHEST ----
  _ex('Barbell Bench Press', category: 'chest', difficulty: 'intermediate',
      primary: 'chest', secondary: 'triceps|shoulders', equipment: 'barbell',
      instructions: 'Lie on a flat bench, grip the bar slightly wider than shoulder-width, lower it to mid-chest, then press back up to full extension.'),
  _ex('Incline Barbell Bench Press', category: 'chest', difficulty: 'intermediate',
      primary: 'chest', secondary: 'shoulders|triceps', equipment: 'barbell',
      instructions: 'On a bench set to 30-45 degrees, lower the bar to your upper chest and press back up.'),
  _ex('Dumbbell Bench Press', category: 'chest', difficulty: 'beginner',
      primary: 'chest', secondary: 'triceps|shoulders', equipment: 'dumbbell',
      instructions: 'Lie flat holding a dumbbell in each hand at chest level, press both up until arms are extended, then lower with control.'),
  _ex('Incline Dumbbell Press', category: 'chest', difficulty: 'beginner',
      primary: 'chest', secondary: 'shoulders', equipment: 'dumbbell',
      instructions: 'On an incline bench, press dumbbells up and slightly inward until arms are extended, then lower slowly.'),
  _ex('Dumbbell Flyes', category: 'chest', difficulty: 'intermediate',
      primary: 'chest', secondary: null, equipment: 'dumbbell',
      instructions: 'Lying flat with a slight bend in the elbows, lower the dumbbells out to the sides in an arc, then bring them back together above the chest.'),
  _ex('Push-Up', category: 'chest', difficulty: 'beginner',
      primary: 'chest', secondary: 'triceps|shoulders|core', equipment: 'bodyweight',
      instructions: 'Hands under shoulders, body in a straight line, lower your chest to the floor and press back up.'),
  _ex('Cable Crossover', category: 'chest', difficulty: 'intermediate',
      primary: 'chest', secondary: null, equipment: 'cable',
      instructions: 'Standing between two cable towers, pull both handles down and across your body in an arc, squeezing the chest at the bottom.'),
  _ex('Chest Dip', category: 'chest', difficulty: 'intermediate',
      primary: 'chest', secondary: 'triceps', equipment: 'bodyweight',
      instructions: 'On parallel bars, lean forward and lower your body until your shoulders are below your elbows, then press back up.'),
  _ex('Machine Chest Press', category: 'chest', difficulty: 'beginner',
      primary: 'chest', secondary: 'triceps', equipment: 'machine',
      instructions: 'Seated at the machine, press the handles forward to full extension, then return with control.'),
  _ex('Decline Bench Press', category: 'chest', difficulty: 'intermediate',
      primary: 'chest', secondary: 'triceps', equipment: 'barbell',
      instructions: 'On a decline bench, lower the bar to your lower chest and press back up.'),

  // ---- BACK ----
  _ex('Deadlift', category: 'back', difficulty: 'advanced',
      primary: 'back|legs', secondary: 'core', equipment: 'barbell',
      instructions: 'Grip the bar just outside your legs, keep your back flat, and stand up by driving through your heels until fully upright.'),
  _ex('Pull-Up', category: 'back', difficulty: 'intermediate',
      primary: 'back', secondary: 'arms', equipment: 'bodyweight',
      instructions: 'Hang from a bar with an overhand grip, pull your chin above the bar, then lower with control.'),
  _ex('Chin-Up', category: 'back', difficulty: 'intermediate',
      primary: 'back', secondary: 'arms', equipment: 'bodyweight',
      instructions: 'Hang from a bar with an underhand grip, pull your chin above the bar, then lower with control.'),
  _ex('Lat Pulldown', category: 'back', difficulty: 'beginner',
      primary: 'back', secondary: 'arms', equipment: 'machine',
      instructions: 'Seated at the machine, pull the bar down to your upper chest, squeezing your shoulder blades together, then release slowly.'),
  _ex('Barbell Row', category: 'back', difficulty: 'intermediate',
      primary: 'back', secondary: 'arms', equipment: 'barbell',
      instructions: 'Hinge at the hips with a flat back, pull the bar up toward your lower ribs, then lower under control.'),
  _ex('Dumbbell Row', category: 'back', difficulty: 'beginner',
      primary: 'back', secondary: 'arms', equipment: 'dumbbell',
      instructions: 'With one knee and hand on a bench, pull a dumbbell up toward your hip, then lower slowly.'),
  _ex('Seated Cable Row', category: 'back', difficulty: 'beginner',
      primary: 'back', secondary: 'arms', equipment: 'cable',
      instructions: 'Seated with feet braced, pull the handle to your torso keeping your back straight, then extend arms slowly.'),
  _ex('T-Bar Row', category: 'back', difficulty: 'intermediate',
      primary: 'back', secondary: 'arms', equipment: 'barbell',
      instructions: 'Straddle the bar, hinge forward, and pull the handle up toward your chest, then lower with control.'),
  _ex('Face Pull', category: 'back', difficulty: 'beginner',
      primary: 'back', secondary: 'shoulders', equipment: 'cable',
      instructions: 'Pull a rope attachment toward your face, flaring your elbows out wide, then return slowly.'),
  _ex('Hyperextension', category: 'back', difficulty: 'beginner',
      primary: 'back', secondary: 'core', equipment: 'bodyweight',
      instructions: 'On a hyperextension bench, lower your torso forward then raise it back to a straight line with your legs.'),

  // ---- LEGS ----
  _ex('Barbell Back Squat', category: 'legs', difficulty: 'intermediate',
      primary: 'legs', secondary: 'core', equipment: 'barbell',
      instructions: 'Bar across your upper back, feet shoulder-width apart, squat down until thighs are at least parallel, then drive back up.'),
  _ex('Front Squat', category: 'legs', difficulty: 'advanced',
      primary: 'legs', secondary: 'core', equipment: 'barbell',
      instructions: 'Bar racked across the front of your shoulders, squat down keeping your torso upright, then stand back up.'),
  _ex('Leg Press', category: 'legs', difficulty: 'beginner',
      primary: 'legs', secondary: null, equipment: 'machine',
      instructions: 'Seated in the machine, lower the platform toward your chest then press it back to full extension without locking knees.'),
  _ex('Romanian Deadlift', category: 'legs', difficulty: 'intermediate',
      primary: 'legs', secondary: 'back', equipment: 'barbell',
      instructions: 'With a slight knee bend, hinge at the hips and lower the bar along your legs, then drive your hips forward to stand.'),
  _ex('Walking Lunge', category: 'legs', difficulty: 'beginner',
      primary: 'legs', secondary: 'core', equipment: 'dumbbell',
      instructions: 'Step forward into a lunge, lowering your back knee toward the floor, then push off into the next step.'),
  _ex('Leg Extension', category: 'legs', difficulty: 'beginner',
      primary: 'legs', secondary: null, equipment: 'machine',
      instructions: 'Seated at the machine, extend your legs to full straightness, then lower with control.'),
  _ex('Leg Curl', category: 'legs', difficulty: 'beginner',
      primary: 'legs', secondary: null, equipment: 'machine',
      instructions: 'Lying or seated at the machine, curl the pad toward your glutes, then lower slowly.'),
  _ex('Bulgarian Split Squat', category: 'legs', difficulty: 'intermediate',
      primary: 'legs', secondary: 'core', equipment: 'dumbbell',
      instructions: 'With your rear foot elevated behind you, lower into a lunge on the front leg, then drive back up.'),
  _ex('Calf Raise', category: 'legs', difficulty: 'beginner',
      primary: 'legs', secondary: null, equipment: 'bodyweight',
      instructions: 'Standing on the balls of your feet, rise up as high as possible, then lower your heels below the step.'),
  _ex('Goblet Squat', category: 'legs', difficulty: 'beginner',
      primary: 'legs', secondary: 'core', equipment: 'dumbbell',
      instructions: 'Hold a dumbbell vertically at your chest, squat down between your knees, then stand back up.'),
  _ex('Hip Thrust', category: 'legs', difficulty: 'intermediate',
      primary: 'legs', secondary: 'core', equipment: 'barbell',
      instructions: 'Upper back on a bench, bar across your hips, drive your hips up until your body forms a straight line, then lower.'),
  _ex('Step-Up', category: 'legs', difficulty: 'beginner',
      primary: 'legs', secondary: null, equipment: 'dumbbell',
      instructions: 'Step onto a bench or box with one leg, driving through the heel to stand fully, then step back down.'),

  // ---- SHOULDERS ----
  _ex('Overhead Press', category: 'shoulders', difficulty: 'intermediate',
      primary: 'shoulders', secondary: 'triceps', equipment: 'barbell',
      instructions: 'Standing with the bar at shoulder height, press it overhead until arms are fully extended, then lower back down.'),
  _ex('Dumbbell Shoulder Press', category: 'shoulders', difficulty: 'beginner',
      primary: 'shoulders', secondary: 'triceps', equipment: 'dumbbell',
      instructions: 'Seated or standing, press dumbbells from shoulder height overhead until arms extend, then lower with control.'),
  _ex('Lateral Raise', category: 'shoulders', difficulty: 'beginner',
      primary: 'shoulders', secondary: null, equipment: 'dumbbell',
      instructions: 'With a slight elbow bend, raise dumbbells out to the sides until level with your shoulders, then lower slowly.'),
  _ex('Front Raise', category: 'shoulders', difficulty: 'beginner',
      primary: 'shoulders', secondary: null, equipment: 'dumbbell',
      instructions: 'Raise a dumbbell straight out in front of you to shoulder height, then lower with control.'),
  _ex('Rear Delt Flye', category: 'shoulders', difficulty: 'beginner',
      primary: 'shoulders', secondary: 'back', equipment: 'dumbbell',
      instructions: 'Bent forward at the hips, raise dumbbells out to the sides, squeezing your rear shoulders, then lower slowly.'),
  _ex('Arnold Press', category: 'shoulders', difficulty: 'intermediate',
      primary: 'shoulders', secondary: 'triceps', equipment: 'dumbbell',
      instructions: 'Start with palms facing you at shoulder height, rotate and press overhead until arms extend, then reverse on the way down.'),
  _ex('Upright Row', category: 'shoulders', difficulty: 'intermediate',
      primary: 'shoulders', secondary: 'back', equipment: 'barbell',
      instructions: 'Pull the bar straight up along your body to chest height, leading with your elbows, then lower slowly.'),
  _ex('Shrugs', category: 'shoulders', difficulty: 'beginner',
      primary: 'shoulders', secondary: null, equipment: 'dumbbell',
      instructions: 'Holding dumbbells at your sides, raise your shoulders straight up toward your ears, then lower with control.'),

  // ---- ARMS ----
  _ex('Barbell Curl', category: 'arms', difficulty: 'beginner',
      primary: 'arms', secondary: null, equipment: 'barbell',
      instructions: 'Standing with an underhand grip, curl the bar up toward your shoulders, then lower with control.'),
  _ex('Dumbbell Curl', category: 'arms', difficulty: 'beginner',
      primary: 'arms', secondary: null, equipment: 'dumbbell',
      instructions: 'Curl a dumbbell in each hand up toward your shoulders, then lower slowly, keeping elbows tucked.'),
  _ex('Hammer Curl', category: 'arms', difficulty: 'beginner',
      primary: 'arms', secondary: null, equipment: 'dumbbell',
      instructions: 'With palms facing each other, curl the dumbbells up toward your shoulders, then lower with control.'),
  _ex('Preacher Curl', category: 'arms', difficulty: 'intermediate',
      primary: 'arms', secondary: null, equipment: 'barbell',
      instructions: 'Arms resting on a preacher bench, curl the bar up, then lower until arms are nearly straight.'),
  _ex('Triceps Pushdown', category: 'arms', difficulty: 'beginner',
      primary: 'arms', secondary: null, equipment: 'cable',
      instructions: 'Elbows tucked at your sides, push the bar or rope down until arms are extended, then return slowly.'),
  _ex('Skull Crusher', category: 'arms', difficulty: 'intermediate',
      primary: 'arms', secondary: null, equipment: 'barbell',
      instructions: 'Lying flat, lower a bar toward your forehead by bending only your elbows, then extend back up.'),
  _ex('Overhead Triceps Extension', category: 'arms', difficulty: 'beginner',
      primary: 'arms', secondary: null, equipment: 'dumbbell',
      instructions: 'Holding a dumbbell overhead with both hands, lower it behind your head by bending your elbows, then extend back up.'),
  _ex('Close-Grip Bench Press', category: 'arms', difficulty: 'intermediate',
      primary: 'arms', secondary: 'chest', equipment: 'barbell',
      instructions: 'With hands closer than shoulder-width, lower the bar to your chest and press back up, keeping elbows tucked.'),
  _ex('Concentration Curl', category: 'arms', difficulty: 'beginner',
      primary: 'arms', secondary: null, equipment: 'dumbbell',
      instructions: 'Seated, brace your elbow against your inner thigh and curl the dumbbell up, then lower slowly.'),
  _ex('Dips (triceps focus)', category: 'arms', difficulty: 'intermediate',
      primary: 'arms', secondary: 'chest', equipment: 'bodyweight',
      instructions: 'On parallel bars with an upright torso, lower your body by bending your elbows, then press back up.'),

  // ---- CORE ----
  _ex('Plank', category: 'core', difficulty: 'beginner',
      primary: 'core', secondary: null, equipment: 'bodyweight',
      instructions: 'Hold a straight line from head to heels, resting on your forearms and toes, keeping your core braced.'),
  _ex('Sit-Up', category: 'core', difficulty: 'beginner',
      primary: 'core', secondary: null, equipment: 'bodyweight',
      instructions: 'Lying with knees bent, curl your torso all the way up toward your knees, then lower back down.'),
  _ex('Crunch', category: 'core', difficulty: 'beginner',
      primary: 'core', secondary: null, equipment: 'bodyweight',
      instructions: 'Lying with knees bent, lift your shoulder blades off the floor by contracting your abs, then lower slowly.'),
  _ex('Russian Twist', category: 'core', difficulty: 'beginner',
      primary: 'core', secondary: null, equipment: 'bodyweight',
      instructions: 'Seated with feet lifted, rotate your torso side to side, touching the floor beside your hips.'),
  _ex('Hanging Leg Raise', category: 'core', difficulty: 'advanced',
      primary: 'core', secondary: null, equipment: 'bodyweight',
      instructions: 'Hanging from a bar, raise your legs to hip height or higher while keeping your torso still, then lower slowly.'),
  _ex('Bicycle Crunch', category: 'core', difficulty: 'beginner',
      primary: 'core', secondary: null, equipment: 'bodyweight',
      instructions: 'Lying down, bring opposite elbow to opposite knee in a pedaling motion, alternating sides.'),
  _ex('Mountain Climber', category: 'core', difficulty: 'beginner',
      primary: 'core', secondary: 'cardio', equipment: 'bodyweight',
      instructions: 'In a plank position, quickly alternate driving your knees toward your chest.'),
  _ex('Ab Wheel Rollout', category: 'core', difficulty: 'advanced',
      primary: 'core', secondary: 'shoulders', equipment: 'other',
      instructions: 'Kneeling, roll the wheel forward as far as you can control, then pull back to the start using your core.'),
  _ex('Side Plank', category: 'core', difficulty: 'intermediate',
      primary: 'core', secondary: null, equipment: 'bodyweight',
      instructions: 'Resting on one forearm and the side of one foot, hold your body in a straight line, then switch sides.'),
  _ex('Cable Woodchopper', category: 'core', difficulty: 'intermediate',
      primary: 'core', secondary: 'shoulders', equipment: 'cable',
      instructions: 'Pull the cable diagonally across your body from high to low (or low to high), rotating through your torso.'),

  // ---- CARDIO ----
  _ex('Running (treadmill)', category: 'cardio', difficulty: 'beginner',
      primary: 'cardio', secondary: 'legs', equipment: 'machine',
      instructions: 'Maintain a steady pace at a challenging but sustainable effort for the target duration.'),
  _ex('Jump Rope', category: 'cardio', difficulty: 'beginner',
      primary: 'cardio', secondary: 'legs', equipment: 'other',
      instructions: 'Turn the rope with your wrists and hop just high enough to clear it, landing softly on the balls of your feet.'),
  _ex('Rowing Machine', category: 'cardio', difficulty: 'beginner',
      primary: 'cardio', secondary: 'back|legs', equipment: 'machine',
      instructions: 'Drive with your legs, then pull the handle to your torso, reversing the sequence smoothly on the return.'),
  _ex('Cycling (stationary)', category: 'cardio', difficulty: 'beginner',
      primary: 'cardio', secondary: 'legs', equipment: 'machine',
      instructions: 'Maintain a steady cadence and resistance appropriate to your target intensity.'),
  _ex('Stair Climber', category: 'cardio', difficulty: 'beginner',
      primary: 'cardio', secondary: 'legs', equipment: 'machine',
      instructions: 'Step continuously at a steady pace, keeping your posture upright rather than leaning on the handles.'),
  _ex('Burpees', category: 'cardio', difficulty: 'intermediate',
      primary: 'cardio', secondary: 'core|legs', equipment: 'bodyweight',
      instructions: 'Drop into a squat, kick your feet back into a plank, return to squat, then jump up explosively.'),
  _ex('High Knees', category: 'cardio', difficulty: 'beginner',
      primary: 'cardio', secondary: 'legs', equipment: 'bodyweight',
      instructions: 'Run in place, driving your knees up toward hip height as quickly as you can.'),
  _ex('Jumping Jacks', category: 'cardio', difficulty: 'beginner',
      primary: 'cardio', secondary: null, equipment: 'bodyweight',
      instructions: 'Jump your feet out while raising your arms overhead, then jump back to the starting position.'),
];

Map<String, Object?> _ex(
  String name, {
  required String category,
  required String difficulty,
  required String primary,
  String? secondary,
  required String equipment,
  required String instructions,
}) {
  return {
    'name': name,
    'category': category,
    'difficulty': difficulty,
    'primary_muscles': primary,
    'secondary_muscles': secondary,
    'equipment': equipment,
    'instructions': instructions,
  };
}
