/// Starter Ghana food dataset — spec Section 7.
///
/// Every entry is honest about its confidence: `verified: 1` means the
/// values are close to a standard reference (USDA FoodData Central or
/// FAO/INFOODS) for a common, less-variable food. `verified: 0` means the
/// values are a reasonable estimate for a home-cooked dish whose recipe
/// (oil quantity, portion, ingredients) varies a lot by household — never
/// present these as lab-certain in the UI.
///
/// This is a real starting set (~90 dishes), not a padded placeholder —
/// per the spec's own philosophy in Section 2. Growing past this is the
/// job of Section 7's sourcing chain: University of Ghana / FRI data,
/// FAO/INFOODS, USDA fallback, then community submission with review.
///
/// Fields match `foods` table columns exactly (see database_helper.dart).
final List<Map<String, Object?>> ghanaFoodSeed = [
  // ---- STAPLES ----
  _food('Jollof Rice (with chicken)', local: 'Jollof', category: 'staple',
      serving: 250, cal: 400, protein: 12, carbs: 55, fat: 14, fiber: 2, sugar: 4, sodium: 600,
      source: 'Estimated from standard recipe'),
  _food('Jollof Rice (plain)', category: 'staple',
      serving: 250, cal: 320, protein: 6, carbs: 58, fat: 8, fiber: 2, sugar: 4, sodium: 480,
      source: 'Estimated from standard recipe'),
  _food('Waakye (rice & beans)', category: 'staple',
      serving: 300, cal: 420, protein: 14, carbs: 70, fat: 9, fiber: 8, sugar: 2, sodium: 450,
      source: 'Estimated from standard recipe'),
  _food('Banku', category: 'staple',
      serving: 200, cal: 280, protein: 5, carbs: 62, fat: 1, fiber: 2, sugar: 0, sodium: 10,
      source: 'Estimated from standard recipe'),
  _food('Fufu (cassava & plantain)', category: 'staple',
      serving: 250, cal: 380, protein: 3, carbs: 90, fat: 0.5, fiber: 3, sugar: 2, sodium: 8,
      source: 'Estimated from standard recipe'),
  _food('Kenkey (Ga)', local: 'Dokono', category: 'staple',
      serving: 200, cal: 280, protein: 5, carbs: 62, fat: 1, fiber: 2, sugar: 0, sodium: 12,
      source: 'Estimated from standard recipe'),
  _food('Tuo Zaafi', local: 'TZ', category: 'staple',
      serving: 250, cal: 300, protein: 6, carbs: 65, fat: 1.5, fiber: 3, sugar: 0, sodium: 10,
      source: 'Estimated from standard recipe'),
  _food('Ampesi (boiled yam & plantain)', category: 'staple',
      serving: 250, cal: 300, protein: 3, carbs: 70, fat: 0.3, fiber: 4, sugar: 2, sodium: 8,
      source: 'Estimated from standard recipe'),
  _food('Kokonte', category: 'staple',
      serving: 200, cal: 260, protein: 2, carbs: 62, fat: 0.3, fiber: 3, sugar: 0, sodium: 6,
      source: 'Estimated from standard recipe'),
  _food('Gari (soaked)', local: 'Gari Foto', category: 'staple',
      serving: 100, cal: 357, protein: 1.2, carbs: 88, fat: 0.3, fiber: 2, sugar: 3, sodium: 5,
      source: 'FAO/INFOODS West African Food Composition Table'),
  _food('Boiled Yam', category: 'staple',
      serving: 200, cal: 240, protein: 3, carbs: 56, fat: 0.2, fiber: 6, sugar: 1, sodium: 12,
      source: 'FAO/INFOODS West African Food Composition Table', verified: true),
  _food('Boiled Plantain', category: 'staple',
      serving: 200, cal: 244, protein: 2.6, carbs: 64, fat: 0.2, fiber: 4, sugar: 30, sodium: 8,
      source: 'USDA FoodData Central', verified: true),
  _food('Fried Plantain (ripe)', local: 'Kelewele-style', category: 'staple',
      serving: 150, cal: 250, protein: 1.5, carbs: 48, fat: 6, fiber: 3, sugar: 22, sodium: 5,
      source: 'Estimated from standard recipe'),
  _food('Rice (plain, boiled)', category: 'staple',
      serving: 200, cal: 260, protein: 5, carbs: 57, fat: 0.5, fiber: 1, sugar: 0, sodium: 4,
      source: 'USDA FoodData Central', verified: true),
  _food('Red Red (bean stew & fried plantain)', category: 'staple',
      serving: 350, cal: 520, protein: 15, carbs: 70, fat: 18, fiber: 10, sugar: 15, sodium: 520,
      source: 'Estimated from standard recipe'),
  _food('Omo Tuo (rice balls)', category: 'staple',
      serving: 250, cal: 330, protein: 6, carbs: 74, fat: 0.5, fiber: 1, sugar: 0, sodium: 6,
      source: 'Estimated from standard recipe'),
  _food('Yam Chips (fried)', category: 'staple',
      serving: 150, cal: 300, protein: 3, carbs: 45, fat: 12, fiber: 4, sugar: 1, sodium: 220,
      source: 'Estimated from standard recipe'),
  _food('Cocoyam (boiled)', category: 'staple',
      serving: 200, cal: 212, protein: 3, carbs: 50, fat: 0.3, fiber: 5, sugar: 2, sodium: 10,
      source: 'FAO/INFOODS West African Food Composition Table'),

  // ---- SOUPS ----
  _food('Light Soup (with meat)', category: 'soup',
      serving: 300, cal: 180, protein: 18, carbs: 6, fat: 9, fiber: 1, sugar: 2, sodium: 550,
      source: 'Estimated from standard recipe'),
  _food('Light Soup (with fish)', category: 'soup',
      serving: 300, cal: 160, protein: 20, carbs: 6, fat: 6, fiber: 1, sugar: 2, sodium: 580,
      source: 'Estimated from standard recipe'),
  _food('Palm Nut Soup', local: 'Abenkwan', category: 'soup',
      serving: 300, cal: 320, protein: 14, carbs: 12, fat: 24, fiber: 3, sugar: 2, sodium: 500,
      source: 'Estimated from standard recipe'),
  _food('Groundnut Soup', category: 'soup',
      serving: 300, cal: 350, protein: 16, carbs: 10, fat: 26, fiber: 2, sugar: 3, sodium: 480,
      source: 'Estimated from standard recipe'),
  _food('Nkatenkwan (groundnut soup with chicken)', category: 'soup',
      serving: 350, cal: 400, protein: 22, carbs: 14, fat: 28, fiber: 3, sugar: 3, sodium: 560,
      source: 'Estimated from standard recipe'),
  _food('Kontomire Stew', local: 'Palava Sauce', category: 'soup',
      serving: 250, cal: 260, protein: 10, carbs: 8, fat: 20, fiber: 4, sugar: 2, sodium: 420,
      source: 'Estimated from standard recipe'),
  _food('Okro Soup', category: 'soup',
      serving: 300, cal: 200, protein: 12, carbs: 10, fat: 12, fiber: 4, sugar: 2, sodium: 460,
      source: 'Estimated from standard recipe'),
  _food('Fetri Detsi (okro stew)', category: 'soup',
      serving: 250, cal: 220, protein: 10, carbs: 12, fat: 14, fiber: 4, sugar: 3, sodium: 440,
      source: 'Estimated from standard recipe'),
  _food('Groundnut Soup with Goat Meat', category: 'soup',
      serving: 350, cal: 420, protein: 24, carbs: 12, fat: 30, fiber: 2, sugar: 3, sodium: 540,
      source: 'Estimated from standard recipe'),

  // ---- PROTEINS ----
  _food('Grilled Tilapia', category: 'protein',
      serving: 200, cal: 280, protein: 40, carbs: 0, fat: 12, fiber: 0, sugar: 0, sodium: 300,
      source: 'USDA FoodData Central', verified: true),
  _food('Fried Tilapia', category: 'protein',
      serving: 200, cal: 340, protein: 38, carbs: 2, fat: 20, fiber: 0, sugar: 0, sodium: 320,
      source: 'Estimated from standard recipe'),
  _food('Grilled Chicken (breast)', category: 'protein',
      serving: 150, cal: 250, protein: 38, carbs: 0, fat: 10, fiber: 0, sugar: 0, sodium: 260,
      source: 'USDA FoodData Central', verified: true),
  _food('Fried Chicken', category: 'protein',
      serving: 150, cal: 320, protein: 30, carbs: 6, fat: 20, fiber: 0, sugar: 0, sodium: 380,
      source: 'Estimated from standard recipe'),
  _food('Goat Meat (light soup style)', local: 'Mutton', category: 'protein',
      serving: 150, cal: 230, protein: 28, carbs: 0, fat: 12, fiber: 0, sugar: 0, sodium: 240,
      source: 'Estimated from standard recipe'),
  _food('Beef Stew Meat', category: 'protein',
      serving: 150, cal: 250, protein: 26, carbs: 2, fat: 15, fiber: 0, sugar: 1, sodium: 300,
      source: 'Estimated from standard recipe'),
  _food('Boiled Eggs', category: 'protein',
      serving: 100, cal: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0, sugar: 1.1, sodium: 124,
      source: 'USDA FoodData Central', verified: true),
  _food('Fried Egg', category: 'protein',
      serving: 100, cal: 196, protein: 14, carbs: 0.8, fat: 15, fiber: 0, sugar: 0.6, sodium: 200,
      source: 'USDA FoodData Central', verified: true),
  _food('Grasscutter Meat', local: 'Akrantie', category: 'protein',
      serving: 150, cal: 210, protein: 30, carbs: 0, fat: 9, fiber: 0, sugar: 0, sodium: 220,
      source: 'Estimated from standard recipe'),
  _food('Smoked Fish', category: 'protein',
      serving: 100, cal: 180, protein: 32, carbs: 0, fat: 5, fiber: 0, sugar: 0, sodium: 620,
      source: 'Estimated from standard recipe'),
  _food('Grilled Sardines', category: 'protein',
      serving: 100, cal: 208, protein: 25, carbs: 0, fat: 11, fiber: 0, sugar: 0, sodium: 380,
      source: 'USDA FoodData Central', verified: true),
  _food('Fried Fish (whole, small)', category: 'protein',
      serving: 150, cal: 310, protein: 30, carbs: 3, fat: 20, fiber: 0, sugar: 0, sodium: 340,
      source: 'Estimated from standard recipe'),

  // ---- SNACKS ----
  _food('Kelewele (spiced fried plantain)', category: 'snack',
      serving: 150, cal: 320, protein: 2, carbs: 48, fat: 14, fiber: 3, sugar: 24, sodium: 180,
      source: 'Estimated from standard recipe'),
  _food('Meat Pie', category: 'snack',
      serving: 120, cal: 340, protein: 10, carbs: 30, fat: 20, fiber: 2, sugar: 3, sodium: 380,
      source: 'Estimated from standard recipe'),
  _food('Bofrot', local: 'Puff-Puff', category: 'snack',
      serving: 100, cal: 300, protein: 5, carbs: 38, fat: 14, fiber: 1, sugar: 10, sodium: 150,
      source: 'Estimated from standard recipe'),
  _food('Chinchinga', local: 'Suya, Kyinkyinga', category: 'snack',
      serving: 100, cal: 220, protein: 20, carbs: 4, fat: 14, fiber: 1, sugar: 1, sodium: 420,
      source: 'Estimated from standard recipe'),
  _food('Plantain Chips', category: 'snack',
      serving: 50, cal: 260, protein: 1, carbs: 32, fat: 14, fiber: 2, sugar: 8, sodium: 140,
      source: 'Estimated from standard recipe'),
  _food('Chin Chin', category: 'snack',
      serving: 50, cal: 240, protein: 3, carbs: 30, fat: 12, fiber: 0.5, sugar: 9, sodium: 90,
      source: 'Estimated from standard recipe'),
  _food('Koose (bean cakes)', local: 'Akara', category: 'snack',
      serving: 100, cal: 230, protein: 8, carbs: 18, fat: 14, fiber: 5, sugar: 1, sodium: 220,
      source: 'Estimated from standard recipe'),
  _food('Roasted Groundnuts', category: 'snack',
      serving: 30, cal: 170, protein: 7, carbs: 6, fat: 14, fiber: 2, sugar: 1, sodium: 5,
      source: 'USDA FoodData Central', verified: true),
  _food('Kuli-Kuli', category: 'snack',
      serving: 30, cal: 150, protein: 8, carbs: 8, fat: 10, fiber: 2, sugar: 1, sodium: 90,
      source: 'Estimated from standard recipe'),
  _food('Roasted Plantain', local: 'Kofi Brokeman', category: 'snack',
      serving: 150, cal: 200, protein: 2, carbs: 48, fat: 0.3, fiber: 3, sugar: 24, sodium: 5,
      source: 'Estimated from standard recipe'),
  _food('Spring Rolls', category: 'snack',
      serving: 100, cal: 260, protein: 6, carbs: 28, fat: 14, fiber: 1, sugar: 2, sodium: 300,
      source: 'Estimated from standard recipe'),

  // ---- BREAKFAST ----
  _food('Koko (millet porridge)', category: 'breakfast',
      serving: 300, cal: 180, protein: 4, carbs: 36, fat: 2, fiber: 3, sugar: 8, sodium: 30,
      source: 'Estimated from standard recipe'),
  _food('Hausa Koko', category: 'breakfast',
      serving: 300, cal: 170, protein: 4, carbs: 34, fat: 2, fiber: 3, sugar: 6, sodium: 30,
      source: 'Estimated from standard recipe'),
  _food('Tom Brown (roasted maize & soya porridge)', category: 'breakfast',
      serving: 300, cal: 220, protein: 8, carbs: 38, fat: 4, fiber: 4, sugar: 10, sodium: 40,
      source: 'Estimated from standard recipe'),
  _food('Bread and Egg', category: 'breakfast',
      serving: 150, cal: 350, protein: 14, carbs: 40, fat: 15, fiber: 2, sugar: 5, sodium: 420,
      source: 'Estimated from standard recipe'),
  _food('Waakye Breakfast Plate', category: 'breakfast',
      serving: 300, cal: 420, protein: 14, carbs: 70, fat: 9, fiber: 8, sugar: 2, sodium: 450,
      source: 'Estimated from standard recipe'),
  _food('Porridge Oats (local style)', category: 'breakfast',
      serving: 250, cal: 180, protein: 6, carbs: 30, fat: 4, fiber: 4, sugar: 6, sodium: 60,
      source: 'Estimated from standard recipe'),
  _food('Fried Yam and Egg Sauce', category: 'breakfast',
      serving: 250, cal: 400, protein: 12, carbs: 46, fat: 18, fiber: 4, sugar: 2, sodium: 380,
      source: 'Estimated from standard recipe'),

  // ---- DRINKS ----
  _food('Sobolo (hibiscus drink)', local: 'Bissap', category: 'drink',
      serving: 300, cal: 90, protein: 0.3, carbs: 22, fat: 0, fiber: 0, sugar: 20, sodium: 5,
      source: 'Estimated from standard recipe'),
  _food('Asaana', category: 'drink',
      serving: 300, cal: 140, protein: 1, carbs: 34, fat: 0.3, fiber: 1, sugar: 28, sodium: 10,
      source: 'Estimated from standard recipe'),
  _food('Palm Wine', category: 'drink',
      serving: 250, cal: 100, protein: 0.5, carbs: 10, fat: 0, fiber: 0, sugar: 8, sodium: 5,
      source: 'Estimated from standard recipe'),
  _food('Coconut Water (fresh)', category: 'drink',
      serving: 250, cal: 45, protein: 1.7, carbs: 9, fat: 0.5, fiber: 2, sugar: 8, sodium: 65,
      source: 'USDA FoodData Central', verified: true),
  _food('Pineapple Juice (fresh)', category: 'drink',
      serving: 250, cal: 110, protein: 1, carbs: 27, fat: 0.3, fiber: 0.5, sugar: 25, sodium: 3,
      source: 'USDA FoodData Central', verified: true),
  _food('Tea (black, with milk & sugar)', category: 'drink',
      serving: 200, cal: 60, protein: 1.5, carbs: 10, fat: 1.5, fiber: 0, sugar: 9, sodium: 15,
      source: 'Estimated from standard recipe'),
  _food('Sugarcane Juice', category: 'drink',
      serving: 250, cal: 180, protein: 0, carbs: 45, fat: 0, fiber: 0, sugar: 42, sodium: 10,
      source: 'Estimated from standard recipe'),
  _food('Watermelon Juice', category: 'drink',
      serving: 250, cal: 65, protein: 1, carbs: 16, fat: 0.3, fiber: 0.5, sugar: 14, sodium: 3,
      source: 'Estimated from standard recipe'),

  // ---- FRUITS ----
  _food('Pineapple (fresh)', category: 'fruit',
      serving: 150, cal: 75, protein: 0.8, carbs: 20, fat: 0.2, fiber: 2, sugar: 15, sodium: 2,
      source: 'USDA FoodData Central', verified: true),
  _food('Mango (fresh)', category: 'fruit',
      serving: 150, cal: 95, protein: 1.2, carbs: 25, fat: 0.6, fiber: 3, sugar: 22, sodium: 2,
      source: 'USDA FoodData Central', verified: true),
  _food('Banana', category: 'fruit',
      serving: 120, cal: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3, sugar: 14, sodium: 1,
      source: 'USDA FoodData Central', verified: true),
  _food('Pawpaw', local: 'Papaya', category: 'fruit',
      serving: 150, cal: 65, protein: 1, carbs: 17, fat: 0.2, fiber: 3, sugar: 11, sodium: 5,
      source: 'USDA FoodData Central', verified: true),
  _food('Orange', category: 'fruit',
      serving: 150, cal: 70, protein: 1.4, carbs: 18, fat: 0.2, fiber: 3.5, sugar: 14, sodium: 1,
      source: 'USDA FoodData Central', verified: true),
  _food('Watermelon', category: 'fruit',
      serving: 200, cal: 60, protein: 1.2, carbs: 15, fat: 0.3, fiber: 1, sugar: 12, sodium: 2,
      source: 'USDA FoodData Central', verified: true),
  _food('Avocado', local: 'Pear', category: 'fruit',
      serving: 100, cal: 160, protein: 2, carbs: 9, fat: 15, fiber: 7, sugar: 0.7, sodium: 7,
      source: 'USDA FoodData Central', verified: true),
  _food('Coconut (fresh meat)', category: 'fruit',
      serving: 80, cal: 280, protein: 3, carbs: 12, fat: 27, fiber: 7, sugar: 5, sodium: 15,
      source: 'USDA FoodData Central', verified: true),
  _food('Guava', category: 'fruit',
      serving: 100, cal: 68, protein: 2.6, carbs: 14, fat: 1, fiber: 5, sugar: 9, sodium: 2,
      source: 'USDA FoodData Central', verified: true),
  _food('Sugar Cane (chewed)', category: 'fruit',
      serving: 100, cal: 90, protein: 0.2, carbs: 24, fat: 0, fiber: 1, sugar: 22, sodium: 5,
      source: 'Estimated from standard recipe'),
  _food('Apple', category: 'fruit',
      serving: 150, cal: 78, protein: 0.4, carbs: 21, fat: 0.3, fiber: 3.6, sugar: 16, sodium: 2,
      source: 'USDA FoodData Central', verified: true),
  _food('Grapes', category: 'fruit',
      serving: 150, cal: 104, protein: 1.1, carbs: 27, fat: 0.3, fiber: 1.4, sugar: 23, sodium: 3,
      source: 'USDA FoodData Central', verified: true),

  // ---- VEGETABLES ----
  _food('Kontomire (cocoyam leaves)', category: 'vegetable',
      serving: 100, cal: 42, protein: 4, carbs: 6, fat: 0.6, fiber: 3, sugar: 1, sodium: 20,
      source: 'FAO/INFOODS West African Food Composition Table'),
  _food('Garden Eggs', local: 'African Eggplant', category: 'vegetable',
      serving: 100, cal: 25, protein: 1.1, carbs: 5.7, fat: 0.2, fiber: 3, sugar: 3, sodium: 2,
      source: 'FAO/INFOODS West African Food Composition Table'),
  _food('Okro (fresh)', category: 'vegetable',
      serving: 100, cal: 33, protein: 2, carbs: 7, fat: 0.2, fiber: 3.2, sugar: 1.5, sodium: 7,
      source: 'USDA FoodData Central', verified: true),
  _food('Cabbage (raw)', category: 'vegetable',
      serving: 100, cal: 25, protein: 1.3, carbs: 6, fat: 0.1, fiber: 2.5, sugar: 3.2, sodium: 18,
      source: 'USDA FoodData Central', verified: true),
  _food('Tomato', category: 'vegetable',
      serving: 100, cal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, sugar: 2.6, sodium: 5,
      source: 'USDA FoodData Central', verified: true),
  _food('Onion', category: 'vegetable',
      serving: 100, cal: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, sugar: 4.2, sodium: 4,
      source: 'USDA FoodData Central', verified: true),
  _food('Scotch Bonnet Pepper', category: 'vegetable',
      serving: 30, cal: 12, protein: 0.6, carbs: 2.7, fat: 0.1, fiber: 0.5, sugar: 1.5, sodium: 1,
      source: 'Estimated from standard recipe'),
  _food('Carrot', category: 'vegetable',
      serving: 100, cal: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, sugar: 4.7, sodium: 69,
      source: 'USDA FoodData Central', verified: true),
  _food('Cucumber', category: 'vegetable',
      serving: 100, cal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, sugar: 1.7, sodium: 2,
      source: 'USDA FoodData Central', verified: true),
  _food('Spinach (local greens)', category: 'vegetable',
      serving: 100, cal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sugar: 0.4, sodium: 79,
      source: 'USDA FoodData Central', verified: true),
];

Map<String, Object?> _food(
  String name, {
  String? local,
  required String category,
  required double serving,
  required double cal,
  required double protein,
  required double carbs,
  required double fat,
  double? fiber,
  double? sugar,
  double? sodium,
  required String source,
  bool verified = false,
}) {
  return {
    'name': name,
    'local_names': local,
    'category': category,
    'serving_size_g': serving,
    'calories': cal,
    'protein_g': protein,
    'carbs_g': carbs,
    'fat_g': fat,
    'fiber_g': fiber,
    'sugar_g': sugar,
    'sodium_mg': sodium,
    'source': source,
    'verified': verified ? 1 : 0,
  };
}
